"""empty message

Revision ID: 899d18676ee5
Revises: 1cc7d74fd32c
Create Date: 2016-07-22 17:14:13.109844

"""

# revision identifiers, used by Alembic.
revision = '899d18676ee5'
down_revision = '1cc7d74fd32c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('store',
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('page',
    sa.Column('page_id', sa.String(), nullable=False),
    sa.Column('page_name', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['fbuser.user_id'], ),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_table('liked',
    sa.Column('liked_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('page_id', sa.String(), nullable=True),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.page_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['fbuser.user_id'], ),
    sa.PrimaryKeyConstraint('liked_id')
    )
    op.create_table('recommendation',
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('from_user_id', sa.String(), nullable=True),
    sa.Column('to_user_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('page_id', sa.String(), nullable=True),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['fbuser.user_id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.page_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['fbuser.user_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    op.drop_table('liked')
    op.drop_table('page')
    op.drop_table('store')
    op.drop_table('product')
    ### end Alembic commands ###
