"""empty message

Revision ID: 96f29d4a1c85
Revises: None
Create Date: 2016-07-16 00:29:03.679949

"""

# revision identifiers, used by Alembic.
revision = '96f29d4a1c85'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('result_all', postgresql.JSON(), nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('liked')
    op.drop_table('fbuser')
    op.drop_table('product')
    op.drop_table('page')
    op.drop_table('recommendation')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation',
    sa.Column('recommendation_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('from_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('to_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_on', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], [u'fbuser.user_id'], name=u'recommendation_from_user_id_fkey'),
    sa.ForeignKeyConstraint(['page_id'], [u'page.page_id'], name=u'recommendation_page_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], [u'product.product_id'], name=u'recommendation_product_id_fkey'),
    sa.ForeignKeyConstraint(['to_user_id'], [u'fbuser.user_id'], name=u'recommendation_to_user_id_fkey'),
    sa.PrimaryKeyConstraint('recommendation_id', name=u'recommendation_pkey')
    )
    op.create_table('page',
    sa.Column('page_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('page_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_on', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], [u'fbuser.user_id'], name=u'page_created_by_fkey'),
    sa.PrimaryKeyConstraint('page_id', name=u'page_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('product',
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('product_id', name=u'product_pkey')
    )
    op.create_table('fbuser',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=u'fbuser_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('liked',
    sa.Column('liked_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_on', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], [u'page.page_id'], name=u'liked_page_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'fbuser.user_id'], name=u'liked_user_id_fkey'),
    sa.PrimaryKeyConstraint('liked_id', name=u'liked_pkey')
    )
    op.drop_table('results')
    ### end Alembic commands ###
