"""empty message

Revision ID: b68b0feb188e
Revises: d80a61b802af
Create Date: 2016-08-24 20:06:26.417710

"""

# revision identifiers, used by Alembic.
revision = 'b68b0feb188e'
down_revision = 'd80a61b802af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('category_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'category_name')
    ### end Alembic commands ###
