"""empty message

Revision ID: 3354e54f60bf
Revises: 899d18676ee5
Create Date: 2016-08-04 02:15:51.390773

"""

# revision identifiers, used by Alembic.
revision = '3354e54f60bf'
down_revision = '899d18676ee5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_page',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('page_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.page_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['fbuser.user_id'], )
    )
    op.drop_table('liked')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked',
    sa.Column('liked_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('page_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_id'], [u'page.page_id'], name=u'liked_page_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'fbuser.user_id'], name=u'liked_user_id_fkey'),
    sa.PrimaryKeyConstraint('liked_id', name=u'liked_pkey')
    )
    op.drop_table('liked_page')
    ### end Alembic commands ###
