"""empty message

Revision ID: 9301b74bd198
Revises: 3354e54f60bf
Create Date: 2016-08-04 02:37:50.894598

"""

# revision identifiers, used by Alembic.
revision = '9301b74bd198'
down_revision = '3354e54f60bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_product',
    sa.Column('page_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.page_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_product')
    ### end Alembic commands ###
